import freshman from '../../fixtures/sample-1-freshman/transcript.txt?raw';
import sophomore from '../../fixtures/sample-2-sophomore/transcript.txt?raw';
import junior from '../../fixtures/sample-3-junior/transcript.txt?raw';
import senior from '../../fixtures/sample-4-senior/transcript.txt?raw';

export interface Sample {
  id: string;
  label: string;
  /** Where the student is, in their own terms. */
  standing: string;
  /** What this snapshot is useful for seeing. */
  blurb: string;
  text: string;
}

/**
 * One invented Information Science student at four points in a four-year
 * degree. Later snapshots contain everything the earlier ones do, so clicking
 * through them shows the same record filling in rather than four unrelated
 * students.
 *
 * The transcripts are generated by `tools/generate-samples.mjs` and checked by
 * `fixtures/samples.test.ts`, which pins each one's cumulative GPA and exactly
 * which requirements are outstanding. Loading one runs the real parser, so the
 * demo cannot drift from what an upload does.
 */
export const SAMPLES: Sample[] = [
  {
    id: 'sample-1-freshman',
    label: 'Freshman',
    standing: 'Two semesters in',
    blurb: 'Most of the major still ahead, and a Gen Ed list that is mostly gaps.',
    text: freshman,
  },
  {
    id: 'sample-2-sophomore',
    label: 'Sophomore',
    standing: 'Halfway through',
    blurb: 'Core courses building up, with a withdrawal on the record.',
    text: sophomore,
  },
  {
    id: 'sample-3-junior',
    label: 'Junior',
    standing: 'Three years done',
    blurb: 'A real Fall 2026 schedule, and one core course left to place.',
    text: junior,
  },
  {
    id: 'sample-4-senior',
    label: 'Senior',
    standing: 'One semester left',
    blurb: 'Everything outstanding is already registered — the audit says so.',
    text: senior,
  },
];

export function findSample(id: string | undefined): Sample | undefined {
  return id ? SAMPLES.find((sample) => sample.id === id) : undefined;
}
