import informationScienceFreshman from '../../fixtures/sample-information-science-freshman/transcript.txt?raw';
import informationScienceSophomore from '../../fixtures/sample-information-science-sophomore/transcript.txt?raw';
import informationScienceJunior from '../../fixtures/sample-information-science-junior/transcript.txt?raw';
import informationScienceSenior from '../../fixtures/sample-information-science-senior/transcript.txt?raw';
import computerScienceFreshman from '../../fixtures/sample-computer-science-freshman/transcript.txt?raw';
import computerScienceSophomore from '../../fixtures/sample-computer-science-sophomore/transcript.txt?raw';
import computerScienceJunior from '../../fixtures/sample-computer-science-junior/transcript.txt?raw';
import computerScienceSenior from '../../fixtures/sample-computer-science-senior/transcript.txt?raw';
import managementFreshman from '../../fixtures/sample-management-freshman/transcript.txt?raw';
import managementSophomore from '../../fixtures/sample-management-sophomore/transcript.txt?raw';
import managementJunior from '../../fixtures/sample-management-junior/transcript.txt?raw';
import managementSenior from '../../fixtures/sample-management-senior/transcript.txt?raw';
import financeFreshman from '../../fixtures/sample-finance-freshman/transcript.txt?raw';
import financeSophomore from '../../fixtures/sample-finance-sophomore/transcript.txt?raw';
import financeJunior from '../../fixtures/sample-finance-junior/transcript.txt?raw';
import financeSenior from '../../fixtures/sample-finance-senior/transcript.txt?raw';
import informationSystemsFreshman from '../../fixtures/sample-information-systems-freshman/transcript.txt?raw';
import informationSystemsSophomore from '../../fixtures/sample-information-systems-sophomore/transcript.txt?raw';
import informationSystemsJunior from '../../fixtures/sample-information-systems-junior/transcript.txt?raw';
import informationSystemsSenior from '../../fixtures/sample-information-systems-senior/transcript.txt?raw';
import psychologyFreshman from '../../fixtures/sample-psychology-freshman/transcript.txt?raw';
import psychologySophomore from '../../fixtures/sample-psychology-sophomore/transcript.txt?raw';
import psychologyJunior from '../../fixtures/sample-psychology-junior/transcript.txt?raw';
import psychologySenior from '../../fixtures/sample-psychology-senior/transcript.txt?raw';

export interface SampleMajor {
  slug: string;
  /** Matches `Transcript.major`, which is what selects the requirements file. */
  name: string;
  /** Column heading; the full name is too wide for six columns. */
  short: string;
  /**
   * Whether a requirements file exists for this major. Psychology deliberately
   * has none, so the grid demonstrates what a student in an un-authored major
   * actually sees rather than leaving that path untested.
   */
  hasRequirements: boolean;
}

export interface SampleYear {
  slug: string;
  label: string;
}

export interface Sample {
  id: string;
  major: string;
  year: string;
  text: string;
}

/**
 * Demo transcripts: one invented student per major, each at four points in a
 * four-year degree. Within a major the four snapshots are the same person, so
 * later ones contain everything the earlier ones do.
 *
 * Generated by `tools/generate-samples.mjs` and checked by
 * `fixtures/samples.test.ts`, which pins every cumulative GPA and how many
 * requirements are outstanding. Loading one runs the real parser, so the demo
 * cannot drift from what an upload does.
 */
export const SAMPLE_MAJORS: SampleMajor[] = [
  { slug: 'information-science', name: 'Information Science', short: 'InfoSci', hasRequirements: true },
  { slug: 'computer-science', name: 'Computer Science', short: 'CS', hasRequirements: true },
  { slug: 'management', name: 'Management', short: 'Management', hasRequirements: true },
  { slug: 'finance', name: 'Finance', short: 'Finance', hasRequirements: true },
  { slug: 'information-systems', name: 'Information Systems', short: 'Info Systems', hasRequirements: true },
  { slug: 'psychology', name: 'Psychology', short: 'Psychology', hasRequirements: false },
];

export const SAMPLE_YEARS: SampleYear[] = [
  { slug: 'freshman', label: 'Freshman' },
  { slug: 'sophomore', label: 'Sophomore' },
  { slug: 'junior', label: 'Junior' },
  { slug: 'senior', label: 'Senior' },
];

export const SAMPLES: Sample[] = [
  { id: 'sample-information-science-freshman', major: 'information-science', year: 'freshman', text: informationScienceFreshman },
  { id: 'sample-information-science-sophomore', major: 'information-science', year: 'sophomore', text: informationScienceSophomore },
  { id: 'sample-information-science-junior', major: 'information-science', year: 'junior', text: informationScienceJunior },
  { id: 'sample-information-science-senior', major: 'information-science', year: 'senior', text: informationScienceSenior },
  { id: 'sample-computer-science-freshman', major: 'computer-science', year: 'freshman', text: computerScienceFreshman },
  { id: 'sample-computer-science-sophomore', major: 'computer-science', year: 'sophomore', text: computerScienceSophomore },
  { id: 'sample-computer-science-junior', major: 'computer-science', year: 'junior', text: computerScienceJunior },
  { id: 'sample-computer-science-senior', major: 'computer-science', year: 'senior', text: computerScienceSenior },
  { id: 'sample-management-freshman', major: 'management', year: 'freshman', text: managementFreshman },
  { id: 'sample-management-sophomore', major: 'management', year: 'sophomore', text: managementSophomore },
  { id: 'sample-management-junior', major: 'management', year: 'junior', text: managementJunior },
  { id: 'sample-management-senior', major: 'management', year: 'senior', text: managementSenior },
  { id: 'sample-finance-freshman', major: 'finance', year: 'freshman', text: financeFreshman },
  { id: 'sample-finance-sophomore', major: 'finance', year: 'sophomore', text: financeSophomore },
  { id: 'sample-finance-junior', major: 'finance', year: 'junior', text: financeJunior },
  { id: 'sample-finance-senior', major: 'finance', year: 'senior', text: financeSenior },
  { id: 'sample-information-systems-freshman', major: 'information-systems', year: 'freshman', text: informationSystemsFreshman },
  { id: 'sample-information-systems-sophomore', major: 'information-systems', year: 'sophomore', text: informationSystemsSophomore },
  { id: 'sample-information-systems-junior', major: 'information-systems', year: 'junior', text: informationSystemsJunior },
  { id: 'sample-information-systems-senior', major: 'information-systems', year: 'senior', text: informationSystemsSenior },
  { id: 'sample-psychology-freshman', major: 'psychology', year: 'freshman', text: psychologyFreshman },
  { id: 'sample-psychology-sophomore', major: 'psychology', year: 'sophomore', text: psychologySophomore },
  { id: 'sample-psychology-junior', major: 'psychology', year: 'junior', text: psychologyJunior },
  { id: 'sample-psychology-senior', major: 'psychology', year: 'senior', text: psychologySenior },
];

export function findSample(id: string | undefined): Sample | undefined {
  return id ? SAMPLES.find((sample) => sample.id === id) : undefined;
}

export function sampleFor(major: string, year: string): Sample | undefined {
  return SAMPLES.find((sample) => sample.major === major && sample.year === year);
}

export function majorOf(id: string | undefined): SampleMajor | undefined {
  const sample = findSample(id);
  return sample ? SAMPLE_MAJORS.find((major) => major.slug === sample.major) : undefined;
}
